spring:
  profiles:
    active: dev
#  security:
#    user:
#      name: dfactory
#      password: Dfactory@2021
  # 国际化资源文件路径
  messages:
    basename: i18n/message

logging:
  level.root: info
  level.cn.com.citydo: info

management:
  endpoints:
    web:
      exposure:
        include: 'loggers'