spring:
  profiles:
    active: dev
#  security:
#    user:
#      name: dfactory
#      password: Dfactory@2021

logging:
  level.root: info
  level.cn.com.citydo: info

management:
  endpoints:
    web:
      exposure:
        include: 'loggers'