
# Spring集成相关
spring:
  datasource:
    # 采用Druid连接池
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:13306/my_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=round
      username: root
      password: j20032004
      # 初始化连接数
      initial-size: 10
      # 最大活跃数
      max-active: 100
      # 请求连接池最大等待时间（单位ms）
      max-wait: 15000
      # 空闲时，最小连接数
      min-idle: 5
      # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT 1 FROM DUAL
      # 申请连接时执行validationQuery检测连接是否有效，开这个配置会降低性能
      test-on-borrow: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据 （单位：ms）
      time-between-eviction-runs-millis: 60000
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      keep-alive: true